### ISSUE TITLE
To-Do List for the First Major Release

### ISSUE THREAD

**Issue by WatDuhHekBro** [WatDuhHekBro/CrossExchange#1]
- [x] Redo the equations used to determine market value.
- [x] Create random events which affect the market.
- [x] Create a custom scheduler that works off random points within each interval.
- [x] Glue it all together.
